[pytest]
testpaths = tests
pythonpath = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --verbose
    --cov=.
    --cov-report=html
    --cov-report=term-missing
    --cov-config=.coveragerc
    --ignore=venv
    --ignore=migrations
    --import-mode=prepend
filterwarnings =
    ignore::DeprecationWarning
markers =
    integration: marks tests as integration tests (requiring database setup)
